export const clothingOptions = {
  prendas_superiores: [
    {
      id: "polo",
      label: "Polo",
      modelPath: "/models/clothes/Polo-draco.glb",
      position: [0, 0, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
    },
    {
      id: "tshirt",
      label: "T-shirt",
      modelPath: "/models/clothes/Tshirt-draco.glb",
      position: [0, 0, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
    },
    {
      id: "chompa",
      label: "Chompa",
      modelPath: "/models/clothes/Chompa-draco.glb",
      position: [0, 0, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
    },
  ],
  prendas_inferiores: [
    {
      id: "sudadera",
      label: "Sudadera",
      modelPath: "/models/clothes/Sudadera-draco.glb",
      position: [0, 0, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
    },
    {
      id: "pantaloneta",
      label: "Pantaloneta",
      modelPath: "/models/clothes/Pantaloneta-draco.glb",
      position: [0, 0, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
    },
    {
      id: "jogger",
      label: "Jogger",
      modelPath: "/models/clothes/Jogger-draco.glb",
      position: [0, 0, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
    },
  ],
  vestidos_de_bano: [
    {
      id: "2piece",
      label: "2 Piezas",
      modelPath: "/models/clothes/2Piece-draco.glb",
      position: [0, 0, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
    },
    {
      id: "entero",
      label: "Entero",
      modelPath: "/models/clothes/Entero-draco.glb",
      position: [0, 0, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
    },
  ],
};
